### PR TITLE
Upgrade OTel to v1.0.0

### PR DESCRIPTION
**Pull request by jbub**

### CODE REVIEW

**Comment by XSAM** [comment]
@jbub Thanks for the PR. Please also update the `CHANGELOG.md`.

**Comment by jbub** [comment]
@XSAM updated

**Review by XSAM — APPROVED** [review]
LGTM. @jbub Thanks for your contribution.

**Comment by jbub** [comment]
Do you think this one is worth a release ?

**Comment by XSAM** [comment]
> Do you think this one is worth a release ?

Yeah, absolutely. I am working on it.

**Comment by jbub** [comment]
Wonderful, sorry to be pushy, i just cant really believe they released 1.0.0 after so looong time 😄

**Comment by XSAM** [comment]
That's fine. I glad we finally make it. 😆

**Pull request merged**
