### PR TITLE
feat(span): Following the OpenTelemetry standards, skip the remote span.

### PR DESCRIPTION
**Pull request by Ccheers**

### CODE REVIEW

**Review by XSAM — CHANGES_REQUESTED** [review]
Hi @Ccheers, thank you for raising a PR. 

However, I am not sure about this change. Could you please elaborate on why this PR follows OpenTelemetry standards and post references to the OpenTelemetry Specification?

**Comment by Ccheers** [comment]
> Hi @Ccheers, thank you for raising a PR.
> 
> However, I am not sure about this change. Could you please elaborate on why this PR follows OpenTelemetry standards and post references to the OpenTelemetry Specification?

https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/context.go#L29
https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/trace_context.go#L72

In the case, if the trace context is propagated remotely through the transport layer, then the context extracted by the Extract operation would be a remote context.

**Comment by XSAM** [comment]
> then the context extracted by the Extract operation would be a remote context.

How is this remote context related to this PR, and the span with such a context needs to be skipped?

**Comment by Ccheers** [comment]
> > then the context extracted by the Extract operation would be a remote context.那么 Extract 操作提取的上下文将是远程上下文。
> 
> How is this remote context related to this PR, and the span with such a context needs to be skipped?这个远程上下文和这个PR有什么关系，有这样上下文的span需要被跳过吗？



> > then the context extracted by the Extract operation would be a remote context.
> 
> How is this remote context related to this PR, and the span with such a context needs to be skipped?
For esample, when you are processing messages through a certain messaging system, you will receive an asynchronous Remote Span Context, which will require handling at that time.

like kafka: https://github.com/dnwe/otelsarama/blob/main/dispatcher.go#L60
this is redis implementation: https://github.com/redis/go-redis/blob/v8.11.5/extra/redisotel/redisotel.go#L44

**Comment by Ccheers** [comment]
You can also implement the recording of a span like this, by using a wrapper function, but this should be a user-side behavior.

```go

func WrapTrace(ctx context.Context, tracer trace.Tracer, textMapPropagator propagation.TextMapPropagator, message *sarama.ConsumerMessage, fn func(ctx context.Context, message *sarama.ConsumerMessage) error) error {
	// Extract a span context from message to link.
	carrier := otelsarama.NewConsumerMessageCarrier(message)
	parentSpanContext := textMapPropagator.Extract(ctx, carrier)

	// Create a span.
	attrs := []attribute.KeyValue{
		semconv.MessagingSystem("kafka"),
		semconv.MessagingDestinationKindTopic,
		semconv.MessagingDestinationName(message.Topic),
		semconv.MessagingOperationReceive,
		semconv.MessagingMessageID(strconv.FormatInt(message.Offset, 10)),
		semconv.MessagingKafkaSourcePartition(int(message.Partition)),
	}
	opts := []trace.SpanStartOption{
		trace.WithAttributes(attrs...),
		trace.WithSpanKind(trace.SpanKindConsumer),
	}
	newCtx, span := tracer.Start(parentSpanContext, fmt.Sprintf("%s handle", message.Topic), opts...)
	defer span.End()
	return fn(newCtx, message)
}

```

**Comment by XSAM** [comment]
I still don't see the benefits of this PR. Could you please elaborate on the benefits of having this PR?

Also, this change breaks the behavior as it fails many tests.

**Comment by Ccheers** [comment]
> I still don't see the benefits of this PR. Could you please elaborate on the benefits of having this PR?
> 
> Also, this change breaks the behavior as it fails many tests.

Yes, it has broken many tests. If this change is necessary for the project, I will attempt to fix it.


From certain perspectives, this can be seen as a complement to the [nonRecordingSpan](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/nonrecording.go#L9); if the incoming context does not require tracing to be [recorded](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/context.go#L38), perhaps we should not initiate a new trace and record it.

**Comment by XSAM** [comment]
I see. This PR is trying to improve the performance of the creation of span. For that, here is my suggestion:

- A PR for performance improvement should never break tests and the behavior.
- This PR should also provide a benchmark with the changed method with a comparison result from `benchstat` that shows the performance gain.

Regarding your suggestion about returning [nonRecordingSpan](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/nonrecording.go#L9) by checking the `IsRecording` method of the parent span. This actually breaks the span creation defined in [opentelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/e87154c02b40e4b7bb6bf776a12e352372b21134/specification/trace/sdk.md#sdk-span-creation).

> Create a span depending on the decision returned by ShouldSample: see description of [ShouldSample's](https://github.com/open-telemetry/opentelemetry-specification/blob/e87154c02b40e4b7bb6bf776a12e352372b21134/specification/trace/sdk.md#shouldsample) return value below for how to set IsRecording and Sampled on the Span, and the [table above](https://github.com/open-telemetry/opentelemetry-specification/blob/e87154c02b40e4b7bb6bf776a12e352372b21134/specification/trace/sdk.md#recording-sampled-reaction-table) on whether to pass the Span to SpanProcessors.

It means you should only know the result of `IsRecording` after the span creation, as it involves the sampler configured by users.

https://github.com/open-telemetry/opentelemetry-go/blob/ba5d1268082fcc4ccb8fa967eb5133fa23e4f2ba/sdk/trace/tracer.go#L87-L94

---

Regarding the [implementation from `go-redis`](https://github.com/redis/go-redis/blob/f3fe61148b2b8fe0a669dc23620690407f5f92af/extra/redisotel/tracing.go#L94-L96), I think this implementation does not comply with the opentelemetry specification. I have created [an issue](https://github.com/redis/go-redis/issues/2953) for this.

**Comment by Ccheers** [comment]
> I see. This PR is trying to improve the performance of the creation of span. For that, here is my suggestion:
> 
> * A PR for performance improvement should never break tests and the behavior.
> * This PR should also provide a benchmark with the changed method with a comparison result from `benchstat` that shows the performance gain.
> 
> Regarding your suggestion about returning [nonRecordingSpan](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/nonrecording.go#L9) by checking the `IsRecording` method of the parent span. This actually breaks the span creation defined in [opentelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/e87154c02b40e4b7bb6bf776a12e352372b21134/specification/trace/sdk.md#sdk-span-creation).
> 
> > Create a span depending on the decision returned by ShouldSample: see description of [ShouldSample's](https://github.com/open-telemetry/opentelemetry-specification/blob/e87154c02b40e4b7bb6bf776a12e352372b21134/specification/trace/sdk.md#shouldsample) return value below for how to set IsRecording and Sampled on the Span, and the [table above](https://github.com/open-telemetry/opentelemetry-specification/blob/e87154c02b40e4b7bb6bf776a12e352372b21134/specification/trace/sdk.md#recording-sampled-reaction-table) on whether to pass the Span to SpanProcessors.
> 
> It means you should only know the result of `IsRecording` after the span creation, as it involves the sampler configured by users.
> 
> https://github.com/open-telemetry/opentelemetry-go/blob/ba5d1268082fcc4ccb8fa967eb5133fa23e4f2ba/sdk/trace/tracer.go#L87-L94
> 
> Regarding the [implementation from `go-redis`](https://github.com/redis/go-redis/blob/f3fe61148b2b8fe0a669dc23620690407f5f92af/extra/redisotel/tracing.go#L94-L96), I think this implementation does not comply with the opentelemetry specification. I have created [an issue](https://github.com/redis/go-redis/issues/2953) for this.


I don't think the approach of redisotel is wrong. The fundamental issue is that otelsql does not handle the [case](https://github.com/open-telemetry/opentelemetry-specification/blob/e87154c02b40e4b7bb6bf776a12e352372b21134/specification/trace/api.md#wrapping-a-spancontext-in-a-span) of nonrecording spans.

**Comment by Ccheers** [comment]
@XSAM I have carefully read through the opentelemetry-specification and you are correct, the ContextWithRemoteSpanContext returns the SpanContext of the parent span. Based on this SpanContext, the generated Span can be recorded. However, if the Context I pass in does not carry a Span, should it not be recorded as a Root trace?

```go

func Test_createSpan(t *testing.T) {
	tp := sdktrace.NewTracerProvider()
	otel.SetTracerProvider(tp)
	cfg := newConfig()

	// caller context is not recording trace
	_, span := createSpan(context.Background(), cfg, "", false, "", nil)
	assert.False(t, span.IsRecording()) // it return true
}

```

**Comment by Ccheers** [comment]
Perhaps this would be better?

```go

func createSpan(
	ctx context.Context,
	cfg config,
	method Method,
	enableDBStatement bool,
	query string,
	args []driver.NamedValue,
) (context.Context, trace.Span) {
        // ignored if parent has no trace
	span := trace.SpanFromContext(ctx)
	if !span.SpanContext().HasTraceID() {
		return ctx, span
	}
         ...
}

```

**Comment by XSAM** [comment]
> However, if the Context I pass in does not carry a Span, should it not be recorded as a Root trace?

It is based on users' configuration of sampling, not our assumption. Assuming users configure an always-on sampler for debugging, then OTel will always create spans regardless of the status of its parent span.

https://github.com/open-telemetry/opentelemetry-go/blob/ba5d1268082fcc4ccb8fa967eb5133fa23e4f2ba/sdk/trace/sampling.go#L128-L130

**Pull request closed without merging**
